# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0001_initial'),
        ('utilisateurs', '0001_initial'),
        ('sujets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.Professionnel'),
        ),
        migrations.AddField(
            model_name='note',
            name='sujet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='sujets.Sujet'),
        ),
    ]
