# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 10:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lieu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Lieu de rencontre',
            },
        ),
        migrations.CreateModel(
            name='Maraude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Date')),
                ('heure_debut', models.TimeField(choices=[(datetime.time(16, 0), 'Après-midi'), (datetime.time(20, 0), 'Soirée')], default=datetime.time(20, 0), verbose_name='Horaire')),
                ('heure_fin', models.TimeField(blank=True, null=True, verbose_name='Terminée à')),
            ],
            options={
                'ordering': ['date'],
                'verbose_name': 'Maraude',
            },
        ),
    ]
