# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 10:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maraudes', '0001_initial'),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('note_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notes.Note')),
            ],
            options={
                'verbose_name': 'Observation',
            },
            bases=('notes.note',),
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi')])),
                ('horaire', models.TimeField(choices=[(datetime.time(16, 0), 'Après-midi'), (datetime.time(20, 0), 'Soirée')], verbose_name='Horaire')),
            ],
            options={
                'verbose_name_plural': 'Planning',
                'verbose_name': 'Jour de maraude',
            },
        ),
        migrations.CreateModel(
            name='Rencontre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_debut', models.TimeField(verbose_name='Heure')),
                ('duree', models.SmallIntegerField(choices=[(5, '5 min'), (10, '10 min'), (15, '15 min'), (20, '20 min'), (30, '30 min'), (45, '45 min'), (60, '1 heure')], verbose_name='Durée')),
                ('lieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maraudes.Lieu')),
                ('maraude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rencontres', to='maraudes.Maraude')),
            ],
            options={
                'ordering': ['maraude', 'heure_debut'],
                'verbose_name': 'Rencontre',
            },
        ),
        migrations.AddField(
            model_name='observation',
            name='rencontre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='maraudes.Rencontre'),
        ),
    ]
